/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Nalog;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import kontroler.KontrolerKI;

/**
 *
 * @author Ivan
 */
public class TimoviForma extends javax.swing.JFrame {
private KontrolerKI kontrolerKI;
    
/**
     * Creates new form TrkeForma
     */
    public TimoviForma() {
        initComponents();
        kontrolerKI=new KontrolerKI();
        kontrolerKI.srediTabeluTim(this,tabelaTimovi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTimovi = new javax.swing.JTable();
        btnPrikazi = new javax.swing.JButton();
        btnDodajTim2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTrke = new javax.swing.JMenu();
        jMenuItemDodajTrku = new javax.swing.JMenuItem();
        jMenuItemPrikaziTrke = new javax.swing.JMenuItem();
        jMenuTimovi = new javax.swing.JMenu();
        jMenuItemDodajTim = new javax.swing.JMenuItem();
        jMenuItemPrikaziTimove = new javax.swing.JMenuItem();
        jMenuVozaci = new javax.swing.JMenu();
        jMenuItemDodajVozaca = new javax.swing.JMenuItem();
        jMenuItemRangVozaca = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemDodajNalog = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu5.setText("jMenu5");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Formula 1 - Timovi");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Timovi"));

        tabelaTimovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaTimovi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnPrikazi.setText("Prikaži tim");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        btnDodajTim2.setText("Dodaj tim");
        btnDodajTim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajTim2ActionPerformed(evt);
            }
        });

        jMenuTrke.setText("Trke");

        jMenuItemDodajTrku.setText("Dodaj");
        jMenuItemDodajTrku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTrkuActionPerformed(evt);
            }
        });
        jMenuTrke.add(jMenuItemDodajTrku);

        jMenuItemPrikaziTrke.setText("Prikaži");
        jMenuItemPrikaziTrke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziTrkeActionPerformed(evt);
            }
        });
        jMenuTrke.add(jMenuItemPrikaziTrke);

        jMenuBar1.add(jMenuTrke);

        jMenuTimovi.setText("Timovi");

        jMenuItemDodajTim.setText("Dodaj");
        jMenuItemDodajTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTimActionPerformed(evt);
            }
        });
        jMenuTimovi.add(jMenuItemDodajTim);

        jMenuItemPrikaziTimove.setText("Prikaži");
        jMenuItemPrikaziTimove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziTimoveActionPerformed(evt);
            }
        });
        jMenuTimovi.add(jMenuItemPrikaziTimove);

        jMenuBar1.add(jMenuTimovi);

        jMenuVozaci.setText("Vozači");

        jMenuItemDodajVozaca.setText("Dodaj");
        jMenuItemDodajVozaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajVozacaActionPerformed(evt);
            }
        });
        jMenuVozaci.add(jMenuItemDodajVozaca);

        jMenuItemRangVozaca.setText("Rang lista ");
        jMenuItemRangVozaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRangVozacaActionPerformed(evt);
            }
        });
        jMenuVozaci.add(jMenuItemRangVozaca);

        jMenuBar1.add(jMenuVozaci);

        jMenu7.setText("Nalog");

        jMenuItemDodajNalog.setText("Dodaj");
        jMenuItemDodajNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajNalogActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemDodajNalog);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(btnPrikazi)
                .addGap(18, 18, 18)
                .addComponent(btnDodajTim2)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikazi)
                    .addComponent(btnDodajTim2))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDodajNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajNalogActionPerformed
NalogDodajForma ndf=new NalogDodajForma(this, true);
ndf.pack();
ndf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajNalogActionPerformed

    private void jMenuItemDodajTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTimActionPerformed
TimDodajForma tdf=new TimDodajForma(this, true);
tdf.pack();
tdf.setVisible(true);

    }//GEN-LAST:event_jMenuItemDodajTimActionPerformed

    private void btnDodajTim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajTim2ActionPerformed
TimDodajForma tdf=new TimDodajForma(this, true);
tdf.pack();
tdf.setVisible(true);

    }//GEN-LAST:event_btnDodajTim2ActionPerformed

    private void jMenuItemPrikaziTimoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziTimoveActionPerformed

    }//GEN-LAST:event_jMenuItemPrikaziTimoveActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
int red=tabelaTimovi.getSelectedRow();
if(red!=-1){
TimDodajForma tdf=new TimDodajForma(this, true);
tdf.pack();
tdf.prikaziTim(red,tabelaTimovi);
tdf.setVisible(true);


}else{
    JOptionPane.showMessageDialog(rootPane, "Niste izabrali tim!");
    return;
}
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void jMenuItemDodajVozacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajVozacaActionPerformed
VozacDodajForma vdf=new VozacDodajForma(this, true);
vdf.pack();
vdf.setVisible(true);

    }//GEN-LAST:event_jMenuItemDodajVozacaActionPerformed

    private void jMenuItemRangVozacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRangVozacaActionPerformed
        VozaciForma vf=new VozaciForma();
        vf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemRangVozacaActionPerformed

    private void jMenuItemPrikaziTrkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziTrkeActionPerformed
        TrkeForma tf=new TrkeForma();
        tf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemPrikaziTrkeActionPerformed

    private void jMenuItemDodajTrkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTrkuActionPerformed
  TrkaPrikazForma tpf=new TrkaPrikazForma();
        tpf.dodajTrku();
        tpf.srediTabeluUcesce();
        tpf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemDodajTrkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimoviForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimoviForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimoviForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimoviForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimoviForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajTim2;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemDodajNalog;
    private javax.swing.JMenuItem jMenuItemDodajTim;
    private javax.swing.JMenuItem jMenuItemDodajTrku;
    private javax.swing.JMenuItem jMenuItemDodajVozaca;
    private javax.swing.JMenuItem jMenuItemPrikaziTimove;
    private javax.swing.JMenuItem jMenuItemPrikaziTrke;
    private javax.swing.JMenuItem jMenuItemRangVozaca;
    private javax.swing.JMenu jMenuTimovi;
    private javax.swing.JMenu jMenuTrke;
    private javax.swing.JMenu jMenuVozaci;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTimovi;
    // End of variables declaration//GEN-END:variables

    public KontrolerKI getKontrolerKI() {
        return kontrolerKI;
    }

    public javax.swing.JTable getTabelaTimovi() {
        return tabelaTimovi;
    }
}
