/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Ucesce;
import domen.Vozac;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import kontroler.KontrolerKI;
import modeli.ModelTabeleUcesce;

/**
 *
 * @author Ivan
 */
public class TrkaPrikazForma extends javax.swing.JFrame {
private KontrolerKI kontrolerKI;
    /**
     * Creates new form TrkaPrikazForma
     */
    public TrkaPrikazForma() {
        initComponents();
        kontrolerKI=new KontrolerKI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDrzava = new javax.swing.JTextField();
        txtKapacitet = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSacuvajTrku = new javax.swing.JButton();
        txtBrKruga = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        txtDatum = new javax.swing.JTextField();
        txtDuzinaKruga = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUcesca = new javax.swing.JTable();
        btnDodajUcesca = new javax.swing.JButton();
        btnObrisiUcesce = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        btnKreirajIzveštaj = new javax.swing.JButton();
        txtStaza = new javax.swing.JTextField();
        btnPrikaziIzveštaje = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTrke = new javax.swing.JMenu();
        jMenuItemDodajTrku = new javax.swing.JMenuItem();
        jMenuItemPrikaziTrke = new javax.swing.JMenuItem();
        jMenuTimovi = new javax.swing.JMenu();
        jMenuItemDodajTim = new javax.swing.JMenuItem();
        jMenuItemPrikaziTimove = new javax.swing.JMenuItem();
        jMenuVozaci = new javax.swing.JMenu();
        jMenuItemDodajVozaca = new javax.swing.JMenuItem();
        jMenuItemRangVozaca = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemDodajNalog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDrzava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrzavaActionPerformed(evt);
            }
        });

        jLabel8.setText("  (dd.mm.yyyy)");

        btnSacuvajTrku.setText("Sačuvaj trku");
        btnSacuvajTrku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajTrkuActionPerformed(evt);
            }
        });

        jButton6.setText("Otkaži");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtDuzinaKruga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuzinaKrugaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Učešća"));
        jPanel1.setToolTipText("");

        tabelaUcesca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaUcesca);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnDodajUcesca.setText("Dodaj učešća");
        btnDodajUcesca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajUcescaActionPerformed(evt);
            }
        });

        btnObrisiUcesce.setText("Obriši učešće");
        btnObrisiUcesce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiUcesceActionPerformed(evt);
            }
        });

        jLabel1.setText("Naziv trke");

        jLabel2.setText("Staza");

        jLabel3.setText("Država");

        jLabel4.setText("Kapacitet tribina");

        jLabel5.setText("Broj krugova");

        jLabel6.setText("Dužina kruga");

        jLabel7.setText("Datum održavanja");

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        btnKreirajIzveštaj.setText("Kreiraj izveštaj");
        btnKreirajIzveštaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajIzveštajActionPerformed(evt);
            }
        });

        btnPrikaziIzveštaje.setText("Prikaži izveštaje incidenata");
        btnPrikaziIzveštaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziIzveštajeActionPerformed(evt);
            }
        });

        jMenuTrke.setText("Trke");

        jMenuItemDodajTrku.setText("Dodaj");
        jMenuTrke.add(jMenuItemDodajTrku);

        jMenuItemPrikaziTrke.setText("Prikaži");
        jMenuItemPrikaziTrke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziTrkeActionPerformed(evt);
            }
        });
        jMenuTrke.add(jMenuItemPrikaziTrke);

        jMenuBar1.add(jMenuTrke);

        jMenuTimovi.setText("Timovi");

        jMenuItemDodajTim.setText("Dodaj");
        jMenuItemDodajTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTimActionPerformed(evt);
            }
        });
        jMenuTimovi.add(jMenuItemDodajTim);

        jMenuItemPrikaziTimove.setText("Prikaži");
        jMenuItemPrikaziTimove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziTimoveActionPerformed(evt);
            }
        });
        jMenuTimovi.add(jMenuItemPrikaziTimove);

        jMenuBar1.add(jMenuTimovi);

        jMenuVozaci.setText("Vozači");

        jMenuItemDodajVozaca.setText("Dodaj");
        jMenuItemDodajVozaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajVozacaActionPerformed(evt);
            }
        });
        jMenuVozaci.add(jMenuItemDodajVozaca);

        jMenuItemRangVozaca.setText("Rang lista ");
        jMenuItemRangVozaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRangVozacaActionPerformed(evt);
            }
        });
        jMenuVozaci.add(jMenuItemRangVozaca);

        jMenuBar1.add(jMenuVozaci);

        jMenu7.setText("Nalog");

        jMenuItemDodajNalog.setText("Dodaj");
        jMenuItemDodajNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajNalogActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemDodajNalog);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacuvajTrku)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKreirajIzveštaj)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNaziv)
                            .addComponent(txtStaza)
                            .addComponent(txtDrzava)
                            .addComponent(txtKapacitet, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnDodajUcesca)
                                .addGap(18, 18, 18)
                                .addComponent(btnObrisiUcesce))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPrikaziIzveštaje)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBrKruga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDuzinaKruga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrKruga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtStaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDuzinaKruga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(btnPrikaziIzveštaje))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajUcesca)
                    .addComponent(btnObrisiUcesce)
                    .addComponent(btnKreirajIzveštaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvajTrku)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPrikaziTrkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziTrkeActionPerformed
 TrkeForma tf=new TrkeForma();
        tf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemPrikaziTrkeActionPerformed

    private void jMenuItemDodajTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTimActionPerformed
        TimDodajForma tdf=new TimDodajForma(this, true);
        tdf.pack();
        tdf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajTimActionPerformed

    private void jMenuItemPrikaziTimoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziTimoveActionPerformed
        TimoviForma tf=new TimoviForma();
        tf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemPrikaziTimoveActionPerformed

    private void jMenuItemDodajVozacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajVozacaActionPerformed
        VozacDodajForma vdf=new VozacDodajForma(this, true);
        vdf.pack();
        vdf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajVozacaActionPerformed

    private void jMenuItemRangVozacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRangVozacaActionPerformed
        VozaciForma vf=new VozaciForma();
        vf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemRangVozacaActionPerformed

    private void jMenuItemDodajNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajNalogActionPerformed
        NalogDodajForma ndf=new NalogDodajForma(this, true);
        ndf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajNalogActionPerformed

    private void txtDrzavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrzavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrzavaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
TrkeForma tf=new TrkeForma();
tf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtDuzinaKrugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuzinaKrugaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuzinaKrugaActionPerformed

    private void btnDodajUcescaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajUcescaActionPerformed
        ModelTabeleUcesce mtu=(ModelTabeleUcesce) tabelaUcesca.getModel();
        ArrayList<Ucesce> listaUcesca=mtu.getLista();
        UcesceForma uf=new UcesceForma(this, true);
        uf.sreditabelu(listaUcesca);
        uf.pack();
        uf.setVisible(true);
    }//GEN-LAST:event_btnDodajUcescaActionPerformed

    private void btnObrisiUcesceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiUcesceActionPerformed
        int red=tabelaUcesca.getSelectedRow();
        if(red!=-1){
            ModelTabeleUcesce mtu=(ModelTabeleUcesce) tabelaUcesca.getModel();
            mtu.obrisi(red);

        }else{
            JOptionPane.showMessageDialog(this, "Niste izabrali učešće!");
            return;
        }
    }//GEN-LAST:event_btnObrisiUcesceActionPerformed

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivActionPerformed

    private void btnSacuvajTrkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajTrkuActionPerformed
kontrolerKI.zapamtiTrku(this,tabelaUcesca,txtBrKruga,txtDatum,txtDrzava,txtDuzinaKruga,txtKapacitet,txtNaziv,txtStaza,btnSacuvajTrku);

    }//GEN-LAST:event_btnSacuvajTrkuActionPerformed

    private void btnPrikaziIzveštajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziIzveštajeActionPerformed
IzvestajiIncidenataPrikaz iip=new IzvestajiIncidenataPrikaz(this, true);
ModelTabeleUcesce mtt=(ModelTabeleUcesce) tabelaUcesca.getModel();
iip.sredi(mtt.getLista().get(0).getTrka());
iip.pack();
iip.setVisible(true);
    }//GEN-LAST:event_btnPrikaziIzveštajeActionPerformed

    private void btnKreirajIzveštajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajIzveštajActionPerformed
 int red=tabelaUcesca.getSelectedRow();
        if(red!=-1){
            ModelTabeleUcesce mtu=(ModelTabeleUcesce) tabelaUcesca.getModel();
            Ucesce u=mtu.getRed(red);
IzvestajIncidentaForma iif=new IzvestajIncidentaForma(this, true);
iif.setUcesce(u);
iif.pack();
iif.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Niste izabrali učešće!");
            return;
        }
    }//GEN-LAST:event_btnKreirajIzveštajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrkaPrikazForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrkaPrikazForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrkaPrikazForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrkaPrikazForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrkaPrikazForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajUcesca;
    private javax.swing.JButton btnKreirajIzveštaj;
    private javax.swing.JButton btnObrisiUcesce;
    private javax.swing.JButton btnPrikaziIzveštaje;
    private javax.swing.JButton btnSacuvajTrku;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDodajNalog;
    private javax.swing.JMenuItem jMenuItemDodajTim;
    private javax.swing.JMenuItem jMenuItemDodajTrku;
    private javax.swing.JMenuItem jMenuItemDodajVozaca;
    private javax.swing.JMenuItem jMenuItemPrikaziTimove;
    private javax.swing.JMenuItem jMenuItemPrikaziTrke;
    private javax.swing.JMenuItem jMenuItemRangVozaca;
    private javax.swing.JMenu jMenuTimovi;
    private javax.swing.JMenu jMenuTrke;
    private javax.swing.JMenu jMenuVozaci;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaUcesca;
    private javax.swing.JTextField txtBrKruga;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtDrzava;
    private javax.swing.JTextField txtDuzinaKruga;
    private javax.swing.JTextField txtKapacitet;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtStaza;
    // End of variables declaration//GEN-END:variables
 void prikaziTrku(int red, JTable tabelaTrke) {
// za sredjivanje forme
kontrolerKI.srediFormuPrikziTrku(red,tabelaTrke,tabelaUcesca,txtBrKruga,txtDatum,txtDrzava,txtDuzinaKruga,txtKapacitet,txtNaziv,txtStaza,btnSacuvajTrku,btnObrisiUcesce,btnDodajUcesca,btnKreirajIzveštaj);
  this.setTitle("Formula 1 - Dodaj trku");
 }


    void izmeniTrku(int red, JTable tabelaTrke) throws Exception {
kontrolerKI.srediFormuIzmeniTrku(this,red,tabelaTrke,tabelaUcesca,txtBrKruga,txtDatum,txtDrzava,txtDuzinaKruga,txtKapacitet,txtNaziv,txtStaza,btnSacuvajTrku,btnObrisiUcesce,btnDodajUcesca,btnPrikaziIzveštaje);
  this.setTitle("Formula 1 - Izmeni trku");
    }
     void dodajTrku(UcesceForma aThis, Vozac v) {
    try {
        ModelTabeleUcesce mtu=(ModelTabeleUcesce) tabelaUcesca.getModel();
        mtu.dodaj(v);
        JOptionPane.showMessageDialog(aThis, "Vozac je dodat!");
    } catch (IOException ex) {
        Logger.getLogger(TrkaPrikazForma.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    public void srediTabeluUcesce() {
         ModelTabeleUcesce mtu=new ModelTabeleUcesce();
           tabelaUcesca.setModel(mtu);
           tabelaUcesca.getColumnModel().getColumn(3).setPreferredWidth(70);
    }

    void dodajTrku() {
// za sredjivanje forme
kontrolerKI.srediFormuDodajTrku(btnPrikaziIzveštaje,btnKreirajIzveštaj);
  this.setTitle("Formula 1 - Dodaj trku");
    }
}
