/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Nalog;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import kontroler.KontrolerKI;

/**
 *
 * @author Ivan
 */
public class TrkeForma extends javax.swing.JFrame {
private KontrolerKI kontrolerKI;

   
    /**
     * Creates new form TrkeForma
     */
    public TrkeForma() {
        initComponents();
        kontrolerKI=new KontrolerKI();
        kontrolerKI.srediTabeluTrke(this,tabelaTrke);
        kontrolerKI.pripremiTabeluTrkeZaSort(this,tabelaTrke,txtFilter);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTrke = new javax.swing.JTable();
        btnPrikaziTrku = new javax.swing.JButton();
        btnDodajTrku = new javax.swing.JButton();
        btnIzmeniTrku = new javax.swing.JButton();
        btnObrisiTrku = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTrke = new javax.swing.JMenu();
        jMenuItemDodajTrku = new javax.swing.JMenuItem();
        jMenuItemPrikaziTrke = new javax.swing.JMenuItem();
        jMenuTimovi = new javax.swing.JMenu();
        jMenuItemDodajTim = new javax.swing.JMenuItem();
        jMenuItemPrikaziTimove = new javax.swing.JMenuItem();
        jMenuVozaci = new javax.swing.JMenu();
        jMenuItemDodajVozaca = new javax.swing.JMenuItem();
        jMenuItemRangVozaca = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemDodajNalog = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu5.setText("jMenu5");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Formula 1 - Trke");

        jLabel1.setText("Pretraži trke");

        txtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trke"));

        tabelaTrke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaTrke);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnPrikaziTrku.setText("Prikaži trku");
        btnPrikaziTrku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziTrkuActionPerformed(evt);
            }
        });

        btnDodajTrku.setText("Dodaj trku");
        btnDodajTrku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajTrkuActionPerformed(evt);
            }
        });

        btnIzmeniTrku.setText("Unesi rezultate");
        btnIzmeniTrku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniTrkuActionPerformed(evt);
            }
        });

        btnObrisiTrku.setText("Obriši trku");
        btnObrisiTrku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiTrkuActionPerformed(evt);
            }
        });

        jMenuTrke.setText("Trke");

        jMenuItemDodajTrku.setText("Dodaj");
        jMenuItemDodajTrku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTrkuActionPerformed(evt);
            }
        });
        jMenuTrke.add(jMenuItemDodajTrku);

        jMenuItemPrikaziTrke.setText("Prikaži");
        jMenuItemPrikaziTrke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziTrkeActionPerformed(evt);
            }
        });
        jMenuTrke.add(jMenuItemPrikaziTrke);

        jMenuBar1.add(jMenuTrke);

        jMenuTimovi.setText("Timovi");

        jMenuItemDodajTim.setText("Dodaj");
        jMenuItemDodajTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTimActionPerformed(evt);
            }
        });
        jMenuTimovi.add(jMenuItemDodajTim);

        jMenuItemPrikaziTimove.setText("Prikaži");
        jMenuItemPrikaziTimove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziTimoveActionPerformed(evt);
            }
        });
        jMenuTimovi.add(jMenuItemPrikaziTimove);

        jMenuBar1.add(jMenuTimovi);

        jMenuVozaci.setText("Vozači");

        jMenuItemDodajVozaca.setText("Dodaj");
        jMenuItemDodajVozaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajVozacaActionPerformed(evt);
            }
        });
        jMenuVozaci.add(jMenuItemDodajVozaca);

        jMenuItemRangVozaca.setText("Rang lista ");
        jMenuItemRangVozaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRangVozacaActionPerformed(evt);
            }
        });
        jMenuVozaci.add(jMenuItemRangVozaca);

        jMenuBar1.add(jMenuVozaci);

        jMenu7.setText("Nalog");

        jMenuItemDodajNalog.setText("Dodaj");
        jMenuItemDodajNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajNalogActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemDodajNalog);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(btnPrikaziTrku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDodajTrku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIzmeniTrku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnObrisiTrku)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikaziTrku)
                    .addComponent(btnDodajTrku)
                    .addComponent(btnIzmeniTrku)
                    .addComponent(btnObrisiTrku))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDodajNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajNalogActionPerformed
NalogDodajForma ndf=new NalogDodajForma(this, true);
ndf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajNalogActionPerformed

    private void jMenuItemDodajTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTimActionPerformed
TimDodajForma tdf=new TimDodajForma(this, true);
tdf.pack();
tdf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajTimActionPerformed

    private void jMenuItemPrikaziTimoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziTimoveActionPerformed
        TimoviForma tf=new TimoviForma();
        tf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemPrikaziTimoveActionPerformed

    private void jMenuItemDodajVozacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajVozacaActionPerformed
VozacDodajForma vdf=new VozacDodajForma(this, true);
vdf.pack();
vdf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajVozacaActionPerformed

    private void jMenuItemRangVozacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRangVozacaActionPerformed
        VozaciForma vf=new VozaciForma();
        vf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemRangVozacaActionPerformed

    private void jMenuItemPrikaziTrkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziTrkeActionPerformed

    }//GEN-LAST:event_jMenuItemPrikaziTrkeActionPerformed

    private void btnPrikaziTrkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziTrkuActionPerformed
int red=tabelaTrke.getSelectedRow();
if(red!=-1){
TrkaPrikazForma tpf=new TrkaPrikazForma();
tpf.prikaziTrku(red,tabelaTrke);
tpf.setVisible(true);
this.setVisible(false);
}else{
    JOptionPane.showMessageDialog(rootPane, "Niste izabrali trku!");
    return;
}
    }//GEN-LAST:event_btnPrikaziTrkuActionPerformed

    private void btnDodajTrkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajTrkuActionPerformed
        TrkaPrikazForma tpf=new TrkaPrikazForma();
        tpf.dodajTrku();
        tpf.srediTabeluUcesce();
        tpf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDodajTrkuActionPerformed

    private void btnIzmeniTrkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniTrkuActionPerformed
int red=tabelaTrke.getSelectedRow();
if(red!=-1){
            TrkaPrikazForma tpf=new TrkaPrikazForma();
    try {
        tpf.izmeniTrku(red,tabelaTrke);
        tpf.setVisible(true);
        this.setVisible(false);
    } catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Vec su uneti rezultati za izabranu trku");
tpf.dispose();
    }


}else{
    JOptionPane.showMessageDialog(rootPane, "Niste izabrali trku!");
    return;
}
    }//GEN-LAST:event_btnIzmeniTrkuActionPerformed

    private void btnObrisiTrkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiTrkuActionPerformed
int red=tabelaTrke.getSelectedRow();
if(red!=-1){
kontrolerKI.obrisiTrku(this,red,tabelaTrke);
}else{
    JOptionPane.showMessageDialog(rootPane, "Niste izabrali trku!");
    return;
}
    }//GEN-LAST:event_btnObrisiTrkuActionPerformed

    private void jMenuItemDodajTrkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTrkuActionPerformed
         TrkaPrikazForma tpf=new TrkaPrikazForma();
        tpf.dodajTrku();
        tpf.srediTabeluUcesce();
        tpf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemDodajTrkuActionPerformed

    private void txtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrkeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrkeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrkeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrkeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrkeForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajTrku;
    private javax.swing.JButton btnIzmeniTrku;
    private javax.swing.JButton btnObrisiTrku;
    private javax.swing.JButton btnPrikaziTrku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemDodajNalog;
    private javax.swing.JMenuItem jMenuItemDodajTim;
    private javax.swing.JMenuItem jMenuItemDodajTrku;
    private javax.swing.JMenuItem jMenuItemDodajVozaca;
    private javax.swing.JMenuItem jMenuItemPrikaziTimove;
    private javax.swing.JMenuItem jMenuItemPrikaziTrke;
    private javax.swing.JMenuItem jMenuItemRangVozaca;
    private javax.swing.JMenu jMenuTimovi;
    private javax.swing.JMenu jMenuTrke;
    private javax.swing.JMenu jMenuVozaci;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTrke;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables

    public KontrolerKI getKontrolerKI() {
        return kontrolerKI;
    }

    public javax.swing.JTable getTabelaTrke() {
        return tabelaTrke;
    }
}
