/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Nalog;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import kontroler.KontrolerKI;

/**
 *
 * @author Ivan
 */
public class VozaciForma extends javax.swing.JFrame {
private KontrolerKI kontrolerKI;
    /**
     * Creates new form TrkeForma
     */
    public VozaciForma() {
        initComponents();
        kontrolerKI=new KontrolerKI();
         
        kontrolerKI.srediTabeluVozaci(this,tabelaVozaci);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        panelVozaci = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVozaci = new javax.swing.JTable();
        btnPrikaziVozaca = new javax.swing.JButton();
        btnDodajVozaca = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTrke = new javax.swing.JMenu();
        jMenuItemDodajTrku = new javax.swing.JMenuItem();
        jMenuItemPrikaziTrke = new javax.swing.JMenuItem();
        jMenuTimovi = new javax.swing.JMenu();
        jMenuItemDodajTim = new javax.swing.JMenuItem();
        jMenuItemPrikaziTimove = new javax.swing.JMenuItem();
        jMenuVozaci = new javax.swing.JMenu();
        jMenuItemDodajVozaca = new javax.swing.JMenuItem();
        jMenuItemRangVozaca = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemDodajNalog = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu5.setText("jMenu5");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Formula 1 - Vozači");

        panelVozaci.setBorder(javax.swing.BorderFactory.createTitledBorder("Generalni plasman"));

        tabelaVozaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaVozaci);

        javax.swing.GroupLayout panelVozaciLayout = new javax.swing.GroupLayout(panelVozaci);
        panelVozaci.setLayout(panelVozaciLayout);
        panelVozaciLayout.setHorizontalGroup(
            panelVozaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        panelVozaciLayout.setVerticalGroup(
            panelVozaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVozaciLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnPrikaziVozaca.setText("Prikaži vozača");
        btnPrikaziVozaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziVozacaActionPerformed(evt);
            }
        });

        btnDodajVozaca.setText("Dodaj vozača");
        btnDodajVozaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajVozacaActionPerformed(evt);
            }
        });

        jMenuTrke.setText("Trke");

        jMenuItemDodajTrku.setText("Dodaj");
        jMenuItemDodajTrku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTrkuActionPerformed(evt);
            }
        });
        jMenuTrke.add(jMenuItemDodajTrku);

        jMenuItemPrikaziTrke.setText("Prikaži");
        jMenuItemPrikaziTrke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziTrkeActionPerformed(evt);
            }
        });
        jMenuTrke.add(jMenuItemPrikaziTrke);

        jMenuBar1.add(jMenuTrke);

        jMenuTimovi.setText("Timovi");

        jMenuItemDodajTim.setText("Dodaj");
        jMenuItemDodajTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajTimActionPerformed(evt);
            }
        });
        jMenuTimovi.add(jMenuItemDodajTim);

        jMenuItemPrikaziTimove.setText("Prikaži");
        jMenuItemPrikaziTimove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziTimoveActionPerformed(evt);
            }
        });
        jMenuTimovi.add(jMenuItemPrikaziTimove);

        jMenuBar1.add(jMenuTimovi);

        jMenuVozaci.setText("Vozači");

        jMenuItemDodajVozaca.setText("Dodaj");
        jMenuItemDodajVozaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajVozacaActionPerformed(evt);
            }
        });
        jMenuVozaci.add(jMenuItemDodajVozaca);

        jMenuItemRangVozaca.setText("Rang lista ");
        jMenuItemRangVozaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRangVozacaActionPerformed(evt);
            }
        });
        jMenuVozaci.add(jMenuItemRangVozaca);

        jMenuBar1.add(jMenuVozaci);

        jMenu7.setText("Nalog");

        jMenuItemDodajNalog.setText("Dodaj");
        jMenuItemDodajNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajNalogActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemDodajNalog);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVozaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnPrikaziVozaca)
                .addGap(18, 18, 18)
                .addComponent(btnDodajVozaca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(panelVozaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikaziVozaca)
                    .addComponent(btnDodajVozaca))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDodajNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajNalogActionPerformed
NalogDodajForma ndf=new NalogDodajForma(this, true);
ndf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajNalogActionPerformed

    private void jMenuItemDodajTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTimActionPerformed
TimDodajForma tdf=new TimDodajForma(this, true);
tdf.pack();
tdf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajTimActionPerformed

    private void jMenuItemPrikaziTimoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziTimoveActionPerformed
        TimoviForma tf=new TimoviForma();
        tf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemPrikaziTimoveActionPerformed

    private void jMenuItemDodajVozacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajVozacaActionPerformed
VozacDodajForma vdf=new VozacDodajForma(this, true);
vdf.pack();
vdf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajVozacaActionPerformed

    private void jMenuItemRangVozacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRangVozacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRangVozacaActionPerformed

    private void btnDodajVozacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajVozacaActionPerformed
VozacDodajForma vdf=new VozacDodajForma(this, true);
vdf.pack();
vdf.setVisible(true);
    }//GEN-LAST:event_btnDodajVozacaActionPerformed

    private void btnPrikaziVozacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziVozacaActionPerformed
int red=tabelaVozaci.getSelectedRow();
if(red!=-1){
VozacDodajForma vdf=new VozacDodajForma(this, true);
vdf.pack();
vdf.prikaziVozaca(red,tabelaVozaci);
vdf.setVisible(true);


}else{
    JOptionPane.showMessageDialog(rootPane, "Niste izabrali vozača!");
    return;
}
    }//GEN-LAST:event_btnPrikaziVozacaActionPerformed

    private void jMenuItemPrikaziTrkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziTrkeActionPerformed
        TrkeForma tf=new TrkeForma();
        tf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemPrikaziTrkeActionPerformed

    private void jMenuItemDodajTrkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTrkuActionPerformed
  TrkaPrikazForma tpf=new TrkaPrikazForma();
        tpf.dodajTrku();
        tpf.srediTabeluUcesce();
        tpf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemDodajTrkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VozaciForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VozaciForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VozaciForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VozaciForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VozaciForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajVozaca;
    private javax.swing.JButton btnPrikaziVozaca;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemDodajNalog;
    private javax.swing.JMenuItem jMenuItemDodajTim;
    private javax.swing.JMenuItem jMenuItemDodajTrku;
    private javax.swing.JMenuItem jMenuItemDodajVozaca;
    private javax.swing.JMenuItem jMenuItemPrikaziTimove;
    private javax.swing.JMenuItem jMenuItemPrikaziTrke;
    private javax.swing.JMenuItem jMenuItemRangVozaca;
    private javax.swing.JMenu jMenuTimovi;
    private javax.swing.JMenu jMenuTrke;
    private javax.swing.JMenu jMenuVozaci;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelVozaci;
    private javax.swing.JTable tabelaVozaci;
    // End of variables declaration//GEN-END:variables

    public KontrolerKI getKontrolerKI() {
        return kontrolerKI;
    }

    public javax.swing.JTable getTabelaVozaci() {
        return tabelaVozaci;
    }
}
